// This file tests to ensure ffmpeg is installed and working properly
// Generated by ChatGPT

const { spawn } = require('child_process');
const ffmpeg = spawn('ffmpeg', ['-version']);

ffmpeg.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});

ffmpeg.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});

ffmpeg.on('close', (code) => {
  console.log(`FFmpeg exited with code ${code}`);
});